# Generated by Django 6.0.3 on 2026-04-23 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_prescribedmedicine'),
        ('pharmacy', '0002_patientcart_patientcartitem_unifiedbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedbill',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
    ]
