# Generated by Django 6.0.3 on 2026-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease_diagnosis',
            field=models.CharField(blank=True, help_text="Doctor's primary diagnosis", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, help_text='Details of medicines prescribed', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_reports',
            field=models.TextField(blank=True, help_text='Notes on any lab tests and their fees/results', null=True),
        ),
    ]
